# Data Exploration

Lets use a real life example to explore the useful data analysis features of pandas. For this purpose, we are going to use the Bike Shairing dataset that is made available on the UCI website. 
Using the various measures those are captured as part of this dataset, lets explore how pandas powerful capabilities can be utilized for the data wrangling and exploration. 

Dataset and more information can be found at following URL - <br>
https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset <br>
Please take some moments to go through the description of the dataset and its features which will be helpful for doing further data analysis.

The Basic Requirements
- Reading Data From CSV
- Formatting, cleaning and filtering Data Frames
- Group-by and Concat / Merge
- Writing Data to CSV

In [1]:
import pandas as pd
import numpy as np

# Step1 - Reading Data From CSV

As the data is stored in csv format, use read_csv function of pandas to read the data in pandas structure named DataFrame.

In [2]:
bikes = pd.read_csv("bike_shairing_hourly.csv")

<b> Data Viewing<b>

Lets explore the first and last few rows of dataframe. 

In [3]:
bikes.head(2)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40

In [4]:
bikes.tail(2)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
17377          48   61  
17378          37   49

Lets find out number of rows and columns of data set.

In [5]:
bikes.shape

(17379, 17)

# Step 2 - Formatting, cleaning and filtering Data Frames

Lets check how many data values are present in each column.

In [6]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     17379 non-null  int64  
 1   dteday      17379 non-null  object 
 2   season      17379 non-null  int64  
 3   yr          17379 non-null  int64  
 4   mnth        17379 non-null  int64  
 5   hr          17379 non-null  int64  
 6   holiday     17379 non-null  int64  
 7   weekday     17379 non-null  int64  
 8   workingday  17379 non-null  int64  
 9   weathersit  17379 non-null  int64  
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64  
 15  registered  17379 non-null  int64  
 16  cnt         17379 non-null  int64  
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


As all the features contains same number of data values, there are no missing values in dataset.

<b> Properties of data <b>

Lets check some properties of dataset :

In [7]:
bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

18 features are present in dataset, most of which looks integers in nature.

In [8]:
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

dteday is datetime field so might need some transformation afterwards.

<b> Unique feature values <b>

Lets explore the unique values present in each feature. These unique values can give us some hints while doing grouping of the data.

In [9]:
bikes.dteday.unique() # two years dates stored from 1 Jan 2011 to 31 Dec 2012

array(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
       '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
       '2011-01-09', '2011-01-10', '2011-01-11', '2011-01-12',
       '2011-01-13', '2011-01-14', '2011-01-15', '2011-01-16',
       '2011-01-17', '2011-01-18', '2011-01-19', '2011-01-20',
       '2011-01-21', '2011-01-22', '2011-01-23', '2011-01-24',
       '2011-01-25', '2011-01-26', '2011-01-27', '2011-01-28',
       '2011-01-29', '2011-01-30', '2011-01-31', '2011-02-01',
       '2011-02-02', '2011-02-03', '2011-02-04', '2011-02-05',
       '2011-02-06', '2011-02-07', '2011-02-08', '2011-02-09',
       '2011-02-10', '2011-02-11', '2011-02-12', '2011-02-13',
       '2011-02-14', '2011-02-15', '2011-02-16', '2011-02-17',
       '2011-02-18', '2011-02-19', '2011-02-20', '2011-02-21',
       '2011-02-22', '2011-02-23', '2011-02-24', '2011-02-25',
       '2011-02-26', '2011-02-27', '2011-02-28', '2011-03-01',
       '2011-03-02', '2011-03-03', '2011-03-04', '2011-

In [10]:
bikes.season.unique()  # four seasons

array([1, 2, 3, 4], dtype=int64)

Same thing can be done using [] operator

In [11]:
bikes["season"].unique()  # four seasons

array([1, 2, 3, 4], dtype=int64)

In [12]:
bikes.yr.unique() # two values - 0 for year 2011 and 1 for year 2012

array([0, 1], dtype=int64)

In [13]:
bikes.mnth.unique() # 12 months data stored

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [14]:
bikes.hr.unique()  # for each day of month, 24 hours data stored

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [15]:
bikes.holiday.unique() #0- no holidy , 1 holiday

array([0, 1], dtype=int64)

In [16]:
bikes.weekday.unique() # each weekday given a number 

array([6, 0, 1, 2, 3, 4, 5], dtype=int64)

In [17]:
bikes.workingday.unique()  # workingday 1 otherwise 0

array([0, 1], dtype=int64)

In [18]:
bikes.weathersit.unique() #weathersit  has four values - 1 , 2, 3, 4

array([1, 2, 3, 4], dtype=int64)

temp, atemp, hum, windspeed are real numbers so will not interested in unique values for it.

casual, registered and cnt are aggregated user counts for each day, so will not be interested in unique values for it.

<b> Missing values identification <b>

Missing values, null values, NaN needs to be identified. 

In [19]:
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [20]:
bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

Individual column can also be chcked for the null values.

In [21]:
bikes.dteday.isnull().sum()

0

None of the feature contains missing values or NaN. 

If null values are present in the dataframe, following code needs to be executed in order to get rid of them.

In [22]:
bikes = bikes.dropna()
#or inplace replacment in data frame
bikes.dropna(inplace=True)
bikes.count()

instant       17379
dteday        17379
season        17379
yr            17379
mnth          17379
hr            17379
holiday       17379
weekday       17379
workingday    17379
weathersit    17379
temp          17379
atemp         17379
hum           17379
windspeed     17379
casual        17379
registered    17379
cnt           17379
dtype: int64

Null values can be removed from individual columns as well. 

In [23]:
bikes.yr.dropna(inplace=True)
bikes.yr.count()

17379

Or missing values can be imputed with some other default values.

In [24]:
bikes.mnth.fillna(0)  #Replace nulls with 0
bikes.mnth.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

<b> Duplicate records identification<b>

Duplicate records needs to be identified and removed.

In [25]:
bikes.duplicated().sum()

0

There are no duplicate records in the data frame.  Same duplicate check can be done on a column as well. 

In [26]:
bikes.instant.duplicated().sum()

0

If duplicate records are present, then following code can be used to remove them.

In [27]:
bikes.drop_duplicates(subset="instant", keep="first", inplace=True)
bikes.count()

instant       17379
dteday        17379
season        17379
yr            17379
mnth          17379
hr            17379
holiday       17379
weekday       17379
workingday    17379
weathersit    17379
temp          17379
atemp         17379
hum           17379
windspeed     17379
casual        17379
registered    17379
cnt           17379
dtype: int64

<b> Data transformation <b>

The datetime column "dte" is captured as object but as it contains date time in it, a lot of interesting things can be dervied from it and added to the existing data frame for further analysis.

In [28]:
bikes.dteday.head()

0    2011-01-01
1    2011-01-01
2    2011-01-01
3    2011-01-01
4    2011-01-01
Name: dteday, dtype: object

Lets convert "dteday" to datetime.

In [29]:
dte = pd.to_datetime(bikes.dteday)
type(dte)

pandas.core.series.Series

<b> Feature Extraction<b>

Now extract year, month and day from "dte" series.

In [30]:
year = dte.dt.year
print(year.head(2))
print(year.tail(2))

0    2011
1    2011
Name: dteday, dtype: int64
17377    2012
17378    2012
Name: dteday, dtype: int64


Add year series into the data frame.

In [31]:
bikes["year"] = year
bikes.year.count()

17379

Same way month, day , weekday features can be extracted from it and added to the dataframe. But our data frame already contains that information so we will not bother about it. 

In [32]:
months = dte.dt.month
days = dte.dt.day
day_of_weeks = dte.dt.dayofweek
day_of_year = dte.dt.dayofyear
weekdays = dte.dt.weekday
week_of_year = dte.dt.weekofyear

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_13056/407755352.py:6: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  week_of_year = dte.dt.weekofyear


<b>Feature Reduction <b>

Some of the features like "instant" does not do any value addition for the analysis apart from identifying the unique record. But same thing can be induced from the row label, hence the "instant" feature can be removed.

In [33]:
bikes.drop(["instant"], axis=1, inplace=True)
bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'year'],
      dtype='object')

Similary, "cnt" attribute can be derived from "casual" and "registered" attributes. So "cnt" is redundant information, hence can be removed.

In [34]:
bikes.drop(["cnt"], axis=1, inplace=True)
bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'year'],
      dtype='object')

<b> Filtering<b>

Lets divide the data frame into two different data frames each one containing different year.

In [35]:
bikes_2011 = bikes[bikes.year == 2011]
bikes_2011.head(2)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  weathersit  \
0  2011-01-01       1   0     1   0        0        6           0           1   
1  2011-01-01       1   0     1   1        0        6           0           1   

   temp   atemp   hum  windspeed  casual  registered  year  
0  0.24  0.2879  0.81        0.0       3          13  2011  
1  0.22  0.2727  0.80        0.0       8          32  2011

In [36]:
bikes_2012 = bikes[bikes.year == 2012]
bikes_2012.head(2)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
8645  2012-01-01       1   1     1   0        0        0           0   
8646  2012-01-01       1   1     1   1        0        0           0   

      weathersit  temp   atemp   hum  windspeed  casual  registered  year  
8645           1  0.36  0.3788  0.66     0.0000       5          43  2012  
8646           1  0.36  0.3485  0.66     0.1343      15          78  2012

Similary several smaller data frames can be derived out of complete data set and then anlysis can be done on those data frames.

In [ ]:
bikes_2011_summer = bikes[(bikes.year == 2011) & (bikes.season == 2)]
bikes_2011_summer.head(2)

In [ ]:
bikes_holiday = bikes[bikes.holiday == 1]
bikes_holiday.head(2)

<b> Quick stat about numeric features<b>

Lets look at the quick statistics about this dataset. 

In [ ]:
bikes.describe()

Lets look at users statistics : 

In [ ]:
bikes.casual.describe()  #casual users stat

In [ ]:
bikes.registered.describe()  #registered users stat

# Step3 - Group-by and Concat /Merge

<b> Group by based on single feature<b>

There are four seasons for which bike shairing data is collected. Lets figure out how many users are using this service as per different seasons.

In [37]:
#First create the group by 
df_by_seasons = bikes.groupby("season")
type(df_by_seasons)

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
#sum("casual") group by season
df_by_seasons["casual"].sum()

In [ ]:
#sum("registered") group by season
df_by_seasons["registered"].sum()

In [ ]:
#sum("registered") group by season , sort in ascending order
df_by_seasons["registered"].sum().sort_values()

In [ ]:
#sum("registered") group by season , sort in descending order
df_by_seasons["registered"].sum().sort_values(ascending=False)

Combine the outcome of two group by into single data frame. 

In [ ]:
#Create the summarized data for casual users
df_casual = df_by_seasons["casual"].sum()
df_casual

In [ ]:
#Create the summarized data for registered users
df_registered = df_by_seasons["registered"].sum()
df_registered

In [ ]:
#Combine the two frames into single one using pandas concat feature
frames = [df_casual, df_registered]
df_seasons = pd.concat(frames, axis=1)
df_seasons

In [ ]:
#Add the rowwise total for each season
df_seasons["total"] = df_seasons["casual"] + df["registered"]
df_seasons

<b> Group by based on multiple features<b>

Lets explore how more than one attributes can be used in group by clause. Average number of users for different years and months can be found as follows :

In [ ]:
#Create the group by based on year and months
df_by_year_months = bikes.groupby(["year", "mnth"])

In [ ]:
#Compute the average number of casual users per month per year
series_casual = df_by_year_months["casual"].mean()
series_casual 

In [ ]:
#Compute the average number of registered users per month per year
series_registered = df_by_year_months["registered"].mean()
series_registered 

In [ ]:
#Concatenate the results of two data frames
df_casual = pd.DataFrame(series_casual)
#df_casual
df_registered = pd.DataFrame(series_registered)
#df_registered
df_year_month = pd.merge(df_casual,df_registered, on=['year', 'mnth'])
df_year_month

In [ ]:
df_year_month["total"] = df_year_month["casual"] + df_year_month["registered"]

In [ ]:
df_year_month

# Step 4 - Writing data frames to CSV file

Lets utilise the pandas function to write back the data frame to CSV file. 

In [ ]:
df_seasons.head()

In [ ]:
df_seasons.to_csv("file1.csv")

In [ ]:
df_year_month.head()

In [ ]:
df_year_month.to_csv("file2.csv")